# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[â•­â”€](bold green)$username in $directory$git_branch$git_status$nodejs$ruby$kubernetes$aws$time$cmd_duration
[â•°â”€](bold green)$character """

# Full path
[directory]
truncation_length = 0

[username]
format = " [$user]($style)"

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[haskell]
format = '\[[$symbol($version)]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[ruby]
symbol = 'ðŸ”º'
format = '\[[$symbol($version)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[â›µ on ($cluster)](green) \]'

[time]
disabled  = false
format = ' --[ $time ]($style)'

